import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="margin-top">
        <div className={styles.chooseStore}>
          <h2>Choose Your Store</h2>
          <div>
            <div>
              <img
                src="https://images-static.nykaa.com/uploads/tr:w-190,e-sharpen,/bf8b0ef1-0520-41e1-9a0b-dee1017d37e9.jpg"
                alt=""
              />
            </div>
            <div>
              <img
                src="https://images-static.nykaa.com/uploads/tr:w-190,e-sharpen,/ce5b4dff-6352-471f-adb4-981e7f6519cd.jpg"
                alt=""
              />
            </div>
            <div>
              <img
                src="https://images-static.nykaa.com/uploads/tr:w-190,e-sharpen,/68872754-3a70-4afc-a6cf-09bf2749d3f5.jpg"
                alt=""
              />
            </div>
            <div>
              <img
                src="https://images-static.nykaa.com/uploads/tr:w-190,e-sharpen,/62f10f14-997c-471f-b070-e77bd04c2ba7.jpg"
                alt=""
              />
            </div>
            <div>
              <img
                src="https://images-static.nykaa.com/uploads/tr:w-190,e-sharpen,/6f2fbf62-53f5-47ed-bc45-40dbef128358.jpg"
                alt=""
              />
            </div>
            <div>
              <img
                src="https://images-static.nykaa.com/uploads/tr:w-190,e-sharpen,/870b9cd2-47e8-4797-a84a-57e38e42370f.jpg"
                alt=""
              />
            </div>
          </div>
        </div>
        <div className={styles.descImg}>
          <img
            src="https://images-static.nykaa.com/uploads/tr:w-1190,e-sharpen,/1a729c4b-19cb-478e-8490-ff5096723577.jpg"
            alt=""
          />
        </div>

        <div className={styles.text}>
          <h4>
            NYKAA FASHION – YOUR ONE-STOP ONLINE SHOPPING SITE FOR CLOTHES,
            ACCESSORIES FOOTWEAR & MORE
          </h4>
          <p>
            Nykaa Fashion online shopping store is India’s one of the finest and
            the best online shopping destination for men, women and kids. Being
            a host to a wide array of lifestyle and fashion brands, Nykaa
            Fashion retails an extensive range of fashion apparels, accessories
            footwear and more for men, women and kids from over 500 plus
            international brands like Vero Moda, Only, Aeropostale, Gap, Puma,
            Adidas, Forever New, American Eagle, etc. and Indian designers like
            Tarun Tahiliani, Ritu Kumar, Varun Bahl, Masaba, etc. Our LUXE store
            brings to you the latest designer collections straight out of the
            fashion houses delivered right to your doorstep. Shop clothes
            online, footwear online, accessories online, lingerie online and
            everything online to save time and most importantly money with Nykaa
            Fashion’s exclusive offers and discounts during seasonal sales and
            more. Get exclusive access to the latest fashion trends, authentic
            designer collections, the newest and most stylish seasonal fashion
            and much more from the comfort of your home with the Nykaa Fashion
            online shopping app. Download the Nykaa Fashion Android app from the
            Play Store or the iOS App from the Apple App Store, where
            accessories, footwear and clothes shopping for you and your family
            will be an absolute delight. From fashion clothing for day to day
            use to occasion-ready clothes for special festivities and wedding
            occasions, Nykaa Fashion online clothing store has got it all for
            you.
          </p>
          <p>
            Also, we at Nykaa Fashion have a section named Style Files where you
            can discover the latest trends in women’s fashion and styling ideas
            to stay in vogue. Thus, if you are looking for women’s fashion wear,
            ladies fashion wear or fashion clothes for girls, you will be
            spoiled for choice as Nykaa Fashion has got it all!
          </p>
        </div>
        <div className={styles.text}>
          <h4>
            SHOP LATEST COLLECTIONS APPARELS, ACCESSORIES AND MORE FOR WOMEN
            ONLINE AT NYKAA FASHION
          </h4>
          <p>
            At Nykaa Fashion online shopping store, you will find a myriad of
            options for men online ranging from casual shirts, trousers, etc. to
            formal suits, blazers, shoes and more. When it comes to men’s
            fashion collection at Nykaa Fashion, you are sure to find plenty of
            options in apparels, accessories, footwear and more that are not
            only trend-led but as well make for a timeless addition to your
            esteemed collection. On your online men’s clothing shopping journey
            at Nykaa Fashion, discover fashion-forward collections from brands
            like Peter England, Arrow, GAP, American Eagle, Louis Philippe and
            many more suited for all your casual, semi-casual and formal needs.
            Explore the latest range on men’s footwear collections ranging from
            formal pairs like dress shoes, brogues, oxfords, loafers and more to
            athletic sneakers, sporty shoes, casual kicks and more from the
            comfort of your home and office with the Nykaa Fashion online
            shopping app. Whether you are online shopping for men for men’s
            bags, belts, wallets, sunglasses, etc. or men’s athletic apparels
            and accessories, Nykaa Fashion online shopping store is sure to be
            your one-stop destination for all.
          </p>
        </div>
      </main>
    </div>
  );
};

export default Home;
